# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en-US"
early_access: true
enable_free_tier: true

reviews:
  profile: "chill"
  request_changes_workflow: true
  high_level_summary: true
  high_level_summary_placeholder: "@coderabbitai summary"
  auto_title_placeholder: "@coderabbitai"
  review_status: true
  poem: false
  collapse_walkthrough: true
  sequence_diagrams: true
  path_instructions:
    - path: "**/*.js"
      instructions: "Please follow JavaScript best practices."
  abort_on_close: true
  auto_review:
    enabled: true
    auto_incremental_review: true
    ignore_title_keywords:
      - "WIP"
      - "Draft"
    drafts: false
    base_branches:
      - "master"
      - "develop"
  tools:
    ast-grep:
      rule_dirs:
        - "rules/"
      util_dirs:
        - "utils/"
      essential_rules: true
      packages:
        - "eslint-plugin"
    shellcheck:
      enabled: true
    ruff:
      enabled: true
    markdownlint:
      enabled: true
    github-checks:
      enabled: true
      timeout_ms: 90000
    languagetool:
      enabled: true
      enabled_rules:
        - "EN_COMMA_PARENTHESIS"
      disabled_rules:
        - "EN_UNPAIRED_QUOTES"
      enabled_categories:
        - "TYPOS"
      disabled_categories:
        - "TYPOGRAPHY"
      enabled_only: false
      level: "default"
    biome:
      enabled: true
    hadolint:
      enabled: true
    swiftlint:
      enabled: true
      config_file: ".swiftlint.yml"
    phpstan:
      enabled: true
      level: "default"
    golangci-lint:
      enabled: true
      config_file: ".golangci.yml"
    yamllint:
      enabled: true
    gitleaks:
      enabled: true
    checkov:
      enabled: true
    detekt:
      enabled: true
      config_file: "detekt.yml"
    eslint:
      enabled: true
    rubocop:
      enabled: true

chat:
  auto_reply: true

knowledge_base:
  opt_out: true
  learnings:
    scope: "auto"
  issues:
    scope: "auto"
