providers = ['node']
buildImage = 'ghcr.io/railwayapp/nixpacks:debian-1734998667'

[variables]
NODE_ENV = 'production'
NPM_CONFIG_PRODUCTION = 'true'
NEXT_TELEMETRY_DISABLED = '1'
NIXPACKS_PATH = '/'

[phases.setup]
nixPkgs = ['nodejs_18', 'yarn_1_22s']

[phases.install]
dependsOn = ['setup']
cmds = ['yarn install --omit=dev', 'yarn prune --production']

[phases.build]
dependsOn = ['install']
cmds = ['yarn run build']


# [start]
# cmd = 'node --max-old-space-size=512 ./node_modules/.bin/next start'
